# Generated by Django 2.1.4 on 2018-12-18 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=100000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
