# Generated by Django 2.1.4 on 2018-12-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='available',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='available',
            name='coupon_id',
        ),
        migrations.RemoveField(
            model_name='available',
            name='shop_id',
        ),
        migrations.DeleteModel(
            name='Available',
        ),
    ]
