# Generated by Django 2.1.4 on 2018-12-20 09:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181219_1913'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='own_coupon',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='own_coupon',
            name='coupon_id',
        ),
        migrations.RemoveField(
            model_name='own_coupon',
            name='user_id',
        ),
        migrations.AddField(
            model_name='coupon',
            name='expired',
            field=models.DateField(default=datetime.date(2020, 1, 1)),
        ),
        migrations.AddField(
            model_name='coupon',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.User'),
        ),
        migrations.DeleteModel(
            name='Own_coupon',
        ),
    ]
