# Generated by Django 2.1.4 on 2018-12-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20181220_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.CharField(choices=[('CAN', 'CAN'), ('PEK', 'PEK'), ('SHA', 'SHA'), ('SZX', 'SZX')], default='CAN', max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='open_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
