# Generated by Django 2.1.4 on 2018-12-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20181221_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_comment',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
