# Generated by Django 2.1.4 on 2018-12-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shop_comment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop_comment',
            old_name='date',
            new_name='comment_date',
        ),
    ]
