# Generated by Django 2.1.4 on 2018-12-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_mark_mark_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
