# Generated by Django 2.1.4 on 2018-12-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_like_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
